// This file is auto generated by build/build-entry.js'
import Alert from './alert'
import Button from './button'
import Popup from './popup'

const version = '1.0.0'

const components = [
  Alert,
  Button,
  Popup
]

const install = Vue => {
  components.forEach(Component => {
    Vue.use(Component)
  })
}

if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

export {
  install,
  version,
  Alert,
  Button,
  Popup
}

export default {
  install,
  version
}
